trailingComma = "es5"
tabWidth = 2
semi = true
singleQuote = true
useTabs = false
jsxSingleQuote = true
bracketSpacing = true
jsxBracketSameLine = false
arrowParens = "always"
proseWrap = "always"
htmlWhitespaceSensitivity = "strict"
