arrowParens = "always"
bracketSpacing = true
htmlWhitespaceSensitivity = "strict"
jsxBracketSameLine = false
jsxSingleQuote = false
proseWrap = "always"
semi = false
singleQuote = true
tabWidth = 2
trailingComma = "es5"
useTabs = false
printWidth = 100
